sudo: required
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install .
  - pip install codecov pytest pytest-cov

script: python -m pytest --cov=formats # cmd to start format validator

after_success:
- codecov
