sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install .
  - pip install codecov pytest pytest-cov
script: python -m pytest --cov=validators

after_success:
- codecov

deploy:
  provider: pypi
  user: "a.ott"
  password:
    secure: "Q0GBGMoy4g3ja1T26iQpgcHhwM2xun8DALpqwNuAwnmgMFAT/QQYDiWTs/Y/dZfpOp3RK56llnt1L5gTVfkp7qKpluu1fV1wTAmvC8EwNGT4MsFpt2xwq2ia21kyPURpNskAZKAioBrTewcHFrSpTewGEV6B6ixrCz5y4pvxHvCR904d6LmgUAJIfws0NffYzX2SAMup+9NraNoRsZ08eV7hb9zSufvlhidbOliDKcMmOzALc/pKEU4Da7+sqBmxB9dR/S+EyWFq66g6EnZIwM+8jfE87Q+k/hWMu6buAWfIUcnU4eDQA2xcloiVoJ0cP2ExbH0h1GOOEQhZNS7XNtB9FkJqJkpikW2bN00IQTWVd7lT84uxWZVTZwMZXOY5iXaRJV3a/gLySzdZQFmfJo91s5WLrsGaQ7+vU02nUUQzY6Q1ilqXkaXLliHDAHN6FWd/B5PhdqvjpXELnsfIeaPjS3+CoEmuvkDsbkgo/BsAIUKw6ENvWOZo8SyGlnvH/ydHcDGf0FSZ5cs22C/5g9He+9MCJpatEKz06nd91W/4N1y39L6QGlv1vZ9Ln/qU6rgtr/tiC90r+ybQlGzL5LXg1ts4kpz/vYbvZcWz+vVhbUvSXoX5UUpEW9HdfNbOaWyufWJB3P0iwZQYX8BWmdluAKpsapIlauAKzKrXf4k="
  on:
    tags: true
