sudo: required
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- cd ${TRAVIS_BUILD_DIR}
- pip install .
- pip install codecov pytest pytest-cov
script: python -m pytest --cov=validators
after_success:
- codecov
deploy:
  provider: pypi
  user: sven1103
  password:
    secure: kkBJ6ST/R1b+wsi0CIN546/Ai4ZnJDAXD+gGjNnJy2hXm8Sk5DueiU7zJSQdwwpkGfisaSZmy5BYwc6gMXBj/r8B/kFQqaRlYVgafDAOHpJ1t0xa3R2WaHWAHfhhV2dS5qRFu1NVHNolgKmc14ugGH4Sb3u6ghqAyrknKI0x51Daew8eLA60XvwPljDoY8hNMRYa4VP3t924UnnhlgLrKMbMWDKphcV+GTykhjek2sOKF6H1epm+ErUBxfRBiWaqXoXu/bioBBvjYfWtnAraxizMa3Dy/jgM55hrABr5SD/kIfKrVbe4eZNYfVQcgBCiEd44ixMdViA5DUD4FhhtGqTsYSg6dywezE0wqUuOOGqj1FOukgpKqFpRXDK3k7dXD8/XR7sF0Aq6AghaNY8qXINRLbdJmLr1WUyYhzpRYgosYfibvhbWPc4m/roO4avJiegkCfkakImjupfImmikJpzA01HGmoXavEeVQWo7PeeYqwzknZeMwPVk2XlS0JVj1002g/ft7JZ8faeGIY8+bCOAuemnc3MPDt3Ox7FUfSeEFu02oJU8yk6KG9TzyzgcDJ1Y4p4FdBwIVSQw9T81AXOBEeXCWe8KpevzBktIaX+ZwQGd9+Lcnt3ov4kwKsi/ds4YstG5tHDbyxiaSb7HlTh70rTVmFqZ+cFhj3PJ9XE=
  on:
    tags: true
